apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: drepkovsky/mealplan-ufe
  newName: drepkovsky/mealplan-ufe
  newTag: 1.0.6 #aktuálna verzia docker obrazu, ktorú chcete aby používatelia - cvičiaci - videli nasadenú

- name: drepkovsky/mealplan-webapi
  newName: drepkovsky/mealplan-webapi
  newTag: 1.0.5


replacements:
- targets:
  - select:
      group: fe.milung.eu
      version: v1
      kind: WebComponent
      name: rrk-mealplan-ufe
    fieldPaths:
    - spec.hash-suffix
  source:
    version: v1
    kind: Deployment
    name: rrk-mealplan-ufe-deployment
    fieldPath: spec.template.spec.containers.0.image
    options:
      delimiter: ":"
      index: 1
